project:
  type: book
  output-dir: docs

book:
  title: "Skriptum - Einführung in die Statistik"
  author: "Robert Rein und Fabian Wunderlich"
  date: "18/03/2025"
  chapters:
    - index.qmd
    - stats_basics.qmd
    - stats_significance.qmd
    - stats_estimation.qmd
    - stats_ttest.qmd
    - stats_anova.qmd
    - stats_correlation.qmd
    - stats_regression.qmd
    - stats_nonparametric.qmd
    - ethics.qmd
    - references.qmd

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    lang: de
    callout-icon: true 
    fig-height: 3
    include-in-header: res/mathjax.html
  pdf:
    documentclass: scrreprt
    fig-height: 2
    include-in-header: 
      text: |
        \usepackage{makeidx,multirow}
        \makeindex
    include-after-body: 
      text: |
        \printindex


